const actionTypes = {
    USER_LOGIN_REQUESTED: 'USER_LOGIN_REQUESTED',
    USER_LOGIN_REJECTED: 'USER_LOGIN_REJECTED',
    USER_LOGIN_FULFILLED: 'USER_LOGIN_FULFILLED',

    USER_LOGOUT_REQUESTED: 'USER_LOGOUT_REQUESTED',
    USER_LOGOUT_REJECTED: 'USER_LOGOUT_REJECTED',
    USER_LOGOUT_FULFILLED: 'USER_LOGOUT_FULFILLED',

    AUTH_STATE_CHANGE: 'AUTH_STATE_CHANGE'
};

export default actionTypes;