export const INCREMENT_ENTHUSIASM = 'INCREMENT_ENTHUSIASM';
export type INCREMENT_ENTHUSIASM = typeof INCREMENT_ENTHUSIASM;

export const DECREMENT_ENTHUSIASM = 'DECREMENT_ENTHUSIASM';
export type DECREMENT_ENTHUSIASM = typeof DECREMENT_ENTHUSIASM;

export const ADD_CLIENT = 'ADD_CLIENT';
export type ADD_CLIENT = typeof ADD_CLIENT;

export const SUBMIT_CLIENT = 'SUBMIT_CLIENT';
export type SUBMIT_CLIENT = typeof SUBMIT_CLIENT;

export const SUBMIT_CLIENT_SUCCESSFUL = 'SUBMIT_CLIENT_SUCCESSFUL';
export type SUBMIT_CLIENT_SUCCESSFUL = typeof SUBMIT_CLIENT_SUCCESSFUL;

export const SUBMIT_CLIENT_FAILED = 'SUBMIT_CLIENT_FAILED';
export type SUBMIT_CLIENT_FAILED = typeof SUBMIT_CLIENT_FAILED;