export const CREATE_CLIENT = 'CREATE_CLIENT';
export type CREATE_CLIENT = typeof CREATE_CLIENT;
export const CREATE_CLIENT_SUCCESSFUL = 'CREATE_CLIENT_SUCCESSFUL';
export type CREATE_CLIENT_SUCCESSFUL = typeof CREATE_CLIENT_SUCCESSFUL;
export const CREATE_CLIENT_FAILED = 'CREATE_CLIENT_FAILED';
export type CREATE_CLIENT_FAILED = typeof CREATE_CLIENT_FAILED;

export const UPDATE_CLIENT = 'UPDATE_CLIENT';
export type UPDATE_CLIENT = typeof UPDATE_CLIENT;
export const UPDATE_CLIENT_SUCCESSFUL = 'UPDATE_CLIENT_SUCCESSFUL';
export type UPDATE_CLIENT_SUCCESSFUL = typeof UPDATE_CLIENT_SUCCESSFUL;
export const UPDATE_CLIENT_FAILED = 'UPDATE_CLIENT_FAILED';
export type UPDATE_CLIENT_FAILED = typeof UPDATE_CLIENT_FAILED;

export const DELETE_CLIENT = 'DELETE_CLIENT';
export type DELETE_CLIENT = typeof DELETE_CLIENT;
export const DELETE_CLIENT_SUCCESSFUL = 'DELETE_CLIENT_SUCCESSFUL';
export type DELETE_CLIENT_SUCCESSFUL = typeof DELETE_CLIENT_SUCCESSFUL;
export const DELETE_CLIENT_FAILED = 'DELETE_CLIENT_FAILED';
export type DELETE_CLIENT_FAILED = typeof DELETE_CLIENT_FAILED;

export const INACTIVE = 'INACTIVE';
export type INACTIVE = typeof INACTIVE;

export const SUBMIT = 'SUBMIT';
export type SUBMIT = typeof SUBMIT;

export const COMPLETE = 'COMPLETE';
export type COMPLETE = typeof COMPLETE;

export const FAIL = 'FAIL';
export type FAIL = typeof FAIL;
