export const SUBMIT_CLIENT = 'SUBMIT_CLIENT';
export type SUBMIT_CLIENT = typeof SUBMIT_CLIENT;

export const SUBMIT_CLIENT_SUCCESSFUL = 'SUBMIT_CLIENT_SUCCESSFUL';
export type SUBMIT_CLIENT_SUCCESSFUL = typeof SUBMIT_CLIENT_SUCCESSFUL;

export const SUBMIT_CLIENT_FAILED = 'SUBMIT_CLIENT_FAILED';
export type SUBMIT_CLIENT_FAILED = typeof SUBMIT_CLIENT_FAILED;

export const DETELE_CLIENT = 'DETELE_CLIENT';
export type DETELE_CLIENT = typeof DETELE_CLIENT;

export const DELETE_CLIENT_SUCCESSFUL = 'DELETE_CLIENT_SUCCESSFUL';
export type DELETE_CLIENT_SUCCESSFUL = typeof DELETE_CLIENT_SUCCESSFUL;

export const DELETE_CLIENT_FAILED = 'DELETE_CLIENT_FAILED';
export type DELETE_CLIENT_FAILED = typeof DELETE_CLIENT_FAILED;

export const INACTIVE = 'INACTIVE';
export type INACTIVE = typeof INACTIVE;

export const SUBMIT = 'SUBMIT';
export type SUBMIT = typeof SUBMIT;

export const COMPLETE = 'COMPLETE';
export type COMPLETE = typeof COMPLETE;

export const FAIL = 'FAIL';
export type FAIL = typeof FAIL;
